dev:
	mode=dev deno run --allow-net --allow-read --allow-env --allow-run --allow-write --import-map=importmap.json --unstable server.js

start: 
	url=https://ultrajs.dev deno run --allow-net --allow-read --allow-env --allow-run --allow-write --import-map=importmap.json --unstable server.js

cache:
	deno cache --reload --no-check server.js